/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clinic;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class BillingFrame extends javax.swing.JFrame {

    /**
     * Creates new form BillingFrame
     */
    public BillingFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        BillingPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        PatientPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        InsProvider = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Breast_Cancer = new javax.swing.JCheckBox();
        Chlamydia_Tests = new javax.swing.JCheckBox();
        Cholesterol_Triglycerides = new javax.swing.JCheckBox();
        Growth_Hormone = new javax.swing.JCheckBox();
        Hepatitis = new javax.swing.JCheckBox();
        Thyroid_Hormone = new javax.swing.JCheckBox();
        Urine_Test = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        Vitamin_B12 = new javax.swing.JCheckBox();
        Pregnancy_Test = new javax.swing.JCheckBox();
        Allergy_Tests = new javax.swing.JCheckBox();
        Blood_Test = new javax.swing.JCheckBox();
        Viral_Tests = new javax.swing.JCheckBox();
        Submit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        dob = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Billing Info");
        setName("BillingFrame"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 37, -1, -1));

        jLabel2.setText("Frist Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Address");

        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });

        LName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameActionPerformed(evt);
            }
        });

        phone.setText("Phone");

        jLabel6.setText("Insurance Provider");

        InsProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsProviderActionPerformed(evt);
            }
        });

        jLabel7.setText("DOB");

        Breast_Cancer.setText("Breast-Cancer ");
        Breast_Cancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Breast_CancerActionPerformed(evt);
            }
        });

        Chlamydia_Tests.setText("Chlamydia-Tests");
        Chlamydia_Tests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chlamydia_TestsActionPerformed(evt);
            }
        });

        Cholesterol_Triglycerides.setText("Cholesterol-Triglycerides");

        Growth_Hormone.setText("Growth-Hormone");

        Hepatitis.setText("Hepatitis");

        Thyroid_Hormone.setText("Thyroid-Hormone");

        Urine_Test.setText("Urine-Test");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Lab Exams");
        jLabel9.setToolTipText("Select Lab Exams to Bill the Patient");

        Vitamin_B12.setText("Vitamin-B12");
        Vitamin_B12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vitamin_B12ActionPerformed(evt);
            }
        });

        Pregnancy_Test.setText("Pregnancy-Test");

        Allergy_Tests.setText("Allergy-Tests");
        Allergy_Tests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Allergy_TestsActionPerformed(evt);
            }
        });

        Blood_Test.setText("Blood-Test");
        Blood_Test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blood_TestActionPerformed(evt);
            }
        });

        Viral_Tests.setText("Viral-Tests ");

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        dob.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM-dd-yyyy"))));

        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("(MM-dd-YYYY)");

        javax.swing.GroupLayout BillingPaneLayout = new javax.swing.GroupLayout(BillingPane);
        BillingPane.setLayout(BillingPaneLayout);
        BillingPaneLayout.setHorizontalGroup(
            BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillingPaneLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Cholesterol_Triglycerides)
                        .addComponent(Growth_Hormone)
                        .addGroup(BillingPaneLayout.createSequentialGroup()
                            .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Chlamydia_Tests)
                                .addComponent(Breast_Cancer))
                            .addGap(59, 59, 59)
                            .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Urine_Test)
                                .addGroup(BillingPaneLayout.createSequentialGroup()
                                    .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Pregnancy_Test)
                                        .addComponent(Thyroid_Hormone)
                                        .addComponent(Hepatitis))
                                    .addGap(39, 39, 39)
                                    .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Viral_Tests)
                                        .addComponent(Blood_Test)
                                        .addComponent(Allergy_Tests)
                                        .addComponent(Vitamin_B12)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillingPaneLayout.createSequentialGroup()
                            .addComponent(Cancel)
                            .addGap(178, 178, 178))))
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(BillingPaneLayout.createSequentialGroup()
                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BillingPaneLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator2))
                    .addGroup(BillingPaneLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(phone)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BillingPaneLayout.createSequentialGroup()
                                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BillingPaneLayout.createSequentialGroup()
                                        .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillingPaneLayout.createSequentialGroup()
                                        .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)))
                                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BillingPaneLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel6))
                                .addGap(27, 27, 27)
                                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InsProvider)
                                    .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                            .addComponent(PatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Submit)
                                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        BillingPaneLayout.setVerticalGroup(
            BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillingPaneLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(InsProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone))
                .addGap(18, 18, 18)
                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Breast_Cancer)
                    .addComponent(Hepatitis)
                    .addComponent(Viral_Tests))
                .addGap(18, 18, 18)
                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chlamydia_Tests)
                    .addComponent(Pregnancy_Test)
                    .addComponent(Vitamin_B12))
                .addGap(18, 18, 18)
                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cholesterol_Triglycerides, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Thyroid_Hormone)
                        .addComponent(Allergy_Tests)))
                .addGap(18, 18, 18)
                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Urine_Test)
                    .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Growth_Hormone)
                        .addComponent(Blood_Test)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(BillingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(Submit))
                .addGap(44, 44, 44))
        );

        getContentPane().add(BillingPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 660, 510));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel8.setText("Bill a Patient");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void LNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameActionPerformed

    private void InsProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsProviderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsProviderActionPerformed

    private void Breast_CancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Breast_CancerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Breast_CancerActionPerformed

    private void Chlamydia_TestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chlamydia_TestsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chlamydia_TestsActionPerformed

    private void Vitamin_B12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vitamin_B12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vitamin_B12ActionPerformed

    private void Blood_TestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blood_TestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Blood_TestActionPerformed

    private void Allergy_TestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Allergy_TestsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Allergy_TestsActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
       
        super.dispose();
     
    }//GEN-LAST:event_CancelActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String firstName = FName.getText();
        String lastName = LName.getText();
        String ph = phone.getText();
        String addr = Address.getText();
        String insProvider = InsProvider.getText();
        String dOBirth = dob.getText();
        
        ArrayList<String> exams = new ArrayList<>();
        
        if(Breast_Cancer.isSelected())exams.add(Breast_Cancer.getText());
        if(Chlamydia_Tests.isSelected())exams.add(Chlamydia_Tests.getText());
        if(Cholesterol_Triglycerides.isSelected())exams.add(Cholesterol_Triglycerides.getText());
        if(Growth_Hormone.isSelected())exams.add(Growth_Hormone.getText());
        if(Hepatitis.isSelected())exams.add(Hepatitis.getText());
        if(Pregnancy_Test.isSelected())exams.add(Pregnancy_Test.getText());
        if(Thyroid_Hormone.isSelected())exams.add(Thyroid_Hormone.getText());
        if(Urine_Test.isSelected())exams.add(Urine_Test.getText());
        if(Viral_Tests.isSelected())exams.add(Viral_Tests.getText());
        if(Vitamin_B12.isSelected())exams.add(Vitamin_B12.getText());
        if(Allergy_Tests.isSelected())exams.add(Allergy_Tests.getText());
        if(Blood_Test.isSelected())exams.add(Blood_Test.getText());
        
        
        if(firstName.length() ==0 || lastName.length() == 0 || ph.length() == 0 || addr.length()==0
               || insProvider.length() == 0 || dOBirth.length() == 0 || exams.isEmpty() )
        {
            JOptionPane.showMessageDialog(null,"Error! You need to fill out all fields. Try again", "Incomplete Fields",JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
            Billing billingForThisPatient = new Billing(firstName, lastName, ph, addr, insProvider, dOBirth, exams);
        
        String output = billingForThisPatient.getFirstName() + "  " + billingForThisPatient.getLastName()+ "    " + "Visit Date: " 
                + billingForThisPatient.getVisitDate() + "\n" + billingForThisPatient.printExamsTakenbyPatient()
                    + "\nTotal Amount: $" + billingForThisPatient.getBalance()  +  "\nInsurance Covered Amount: $" 
                    + billingForThisPatient.getAmountCovered() + "\nBalance owed: $" + billingForThisPatient.getNetBalance()+ "\n\n";
        JOptionPane.showMessageDialog(null, output, "Patient's Billing Info",JOptionPane.INFORMATION_MESSAGE);
        super.dispose();
        }
        
        
        
                
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JCheckBox Allergy_Tests;
    private javax.swing.JPanel BillingPane;
    private javax.swing.JCheckBox Blood_Test;
    private javax.swing.JCheckBox Breast_Cancer;
    private javax.swing.JButton Cancel;
    private javax.swing.JCheckBox Chlamydia_Tests;
    private javax.swing.JCheckBox Cholesterol_Triglycerides;
    private javax.swing.JTextField FName;
    private javax.swing.JCheckBox Growth_Hormone;
    private javax.swing.JCheckBox Hepatitis;
    private javax.swing.JTextField InsProvider;
    private javax.swing.JTextField LName;
    private javax.swing.JTextField PatientPhone;
    private javax.swing.JCheckBox Pregnancy_Test;
    private javax.swing.JButton Submit;
    private javax.swing.JCheckBox Thyroid_Hormone;
    private javax.swing.JCheckBox Urine_Test;
    private javax.swing.JCheckBox Viral_Tests;
    private javax.swing.JCheckBox Vitamin_B12;
    private javax.swing.JFormattedTextField dob;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel phone;
    // End of variables declaration//GEN-END:variables
}
