/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clinic;

import javax.swing.JFrame;

/**
 *
 * @author Andres
 */
public class MainClinicFrame extends javax.swing.JFrame {

    /**
     * Creates new form AJJ_Clinic_Frame
     */
    public MainClinicFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jPopupMenu6 = new javax.swing.JPopupMenu();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        DoctorMainMenu = new javax.swing.JMenu();
        NewDoctor = new javax.swing.JMenuItem();
        ListOfDoctors = new javax.swing.JMenuItem();
        SearchDoctor = new javax.swing.JMenuItem();
        RemoveDoctor = new javax.swing.JMenuItem();
        PatientMainMenu = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        NewPatient = new javax.swing.JMenuItem();
        ListOfPatients = new javax.swing.JMenuItem();
        Insurance = new javax.swing.JMenuItem();
        SearchPatient = new javax.swing.JMenuItem();
        RemovePatient = new javax.swing.JMenuItem();
        AppointmentMainMenu = new javax.swing.JMenu();
        NewAppointment = new javax.swing.JMenuItem();
        ListOfAppointments = new javax.swing.JMenuItem();
        Billing = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenuItem10.setText("jMenuItem10");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem13.setText("jMenuItem13");

        jMenu7.setText("jMenu7");

        jMenuItem14.setText("jMenuItem14");

        jMenuItem15.setText("jMenuItem15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andy\\Desktop\\pics\\startrek medical.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("AJA Clinic");

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Where your future is secure");

        DoctorMainMenu.setText("Doctor");

        NewDoctor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        NewDoctor.setText("New Doctor");
        NewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewDoctorActionPerformed(evt);
            }
        });
        DoctorMainMenu.add(NewDoctor);

        ListOfDoctors.setText("List of Doctors");
        ListOfDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListOfDoctorsActionPerformed(evt);
            }
        });
        DoctorMainMenu.add(ListOfDoctors);

        SearchDoctor.setText("Search Doctor");
        SearchDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDoctorActionPerformed(evt);
            }
        });
        DoctorMainMenu.add(SearchDoctor);

        RemoveDoctor.setText("Remove a Doctor");
        RemoveDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveDoctorActionPerformed(evt);
            }
        });
        DoctorMainMenu.add(RemoveDoctor);

        jMenuBar1.add(DoctorMainMenu);

        PatientMainMenu.setText("Patient");
        PatientMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientMainMenuActionPerformed(evt);
            }
        });
        PatientMainMenu.add(jSeparator1);

        NewPatient.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        NewPatient.setText("New Patient ");
        NewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPatientActionPerformed(evt);
            }
        });
        PatientMainMenu.add(NewPatient);

        ListOfPatients.setText("List of Patients");
        ListOfPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListOfPatientsActionPerformed(evt);
            }
        });
        PatientMainMenu.add(ListOfPatients);

        Insurance.setText("Insurance");
        Insurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsuranceActionPerformed(evt);
            }
        });
        PatientMainMenu.add(Insurance);

        SearchPatient.setText("Search Patient");
        SearchPatient.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                SearchPatientAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        SearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPatientActionPerformed(evt);
            }
        });
        PatientMainMenu.add(SearchPatient);

        RemovePatient.setText("Remove Patient");
        RemovePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovePatientActionPerformed(evt);
            }
        });
        PatientMainMenu.add(RemovePatient);

        jMenuBar1.add(PatientMainMenu);

        AppointmentMainMenu.setText("Appointment");

        NewAppointment.setText("New Appointment");
        NewAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAppointmentActionPerformed(evt);
            }
        });
        AppointmentMainMenu.add(NewAppointment);

        ListOfAppointments.setText("List of Appointments");
        ListOfAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListOfAppointmentsActionPerformed(evt);
            }
        });
        AppointmentMainMenu.add(ListOfAppointments);

        jMenuBar1.add(AppointmentMainMenu);

        Billing.setText("Billing");
        Billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingActionPerformed(evt);
            }
        });

        jMenuItem21.setText("Billing Info");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        Billing.add(jMenuItem21);

        jMenuBar1.add(Billing);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewDoctorActionPerformed
        NewDoctor doctorFrame = new NewDoctor();
        doctorFrame.setVisible(true);
       
        
    }//GEN-LAST:event_NewDoctorActionPerformed

    private void SearchDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDoctorActionPerformed
        SearchDoctor SearchDr = new SearchDoctor();
        SearchDr.setSize(500,600);
        SearchDr.setVisible(true);
        
    }//GEN-LAST:event_SearchDoctorActionPerformed

    private void NewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPatientActionPerformed
        // TODO add your handling code here:
        NewPatient newPatient = new NewPatient();
        newPatient.setVisible(true);
    }//GEN-LAST:event_NewPatientActionPerformed

    private void ListOfPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListOfPatientsActionPerformed
        // TODO add your handling code here:
        ListOfPatients pt = new ListOfPatients();
        pt.setSize(600,600);
        pt.setVisible(true);
    }//GEN-LAST:event_ListOfPatientsActionPerformed

    private void BillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingActionPerformed
        // TODO add your handling code here:
        JFrame billingFrame = new JFrame("Billing Info");
        billingFrame.setSize(300, 300);
        billingFrame.setVisible(true);
        
    }//GEN-LAST:event_BillingActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        BillingFrame billingFrame = new BillingFrame();
        billingFrame.setVisible(true);
              
        
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void ListOfDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListOfDoctorsActionPerformed
       ListOfDoctors newListOfDoctors = new ListOfDoctors();
       newListOfDoctors.setVisible(true);
       newListOfDoctors.setSize(600, 600);
    }//GEN-LAST:event_ListOfDoctorsActionPerformed

    private void RemoveDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveDoctorActionPerformed
        // TODO add your handling code here:
        RemoveDoctor remDr = new RemoveDoctor();
        remDr.setVisible(true);
    }//GEN-LAST:event_RemoveDoctorActionPerformed

    private void InsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsuranceActionPerformed
        // TODO add your handling code here:
        Insurance ins = new Insurance();
        ins.setSize(700,600);
        ins.setVisible(true);
    }//GEN-LAST:event_InsuranceActionPerformed

    private void SearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPatientActionPerformed
        // TODO add your handling code here:
        SearchPatients pt = new SearchPatients();
        pt.setSize(700, 600);
        pt.setVisible(true);
    }//GEN-LAST:event_SearchPatientActionPerformed

    private void SearchPatientAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_SearchPatientAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchPatientAncestorAdded

    private void PatientMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientMainMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PatientMainMenuActionPerformed

    private void RemovePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovePatientActionPerformed
        // TODO add your handling code here:
        RemovePatient remPt = new RemovePatient();
        remPt.setSize(700, 600);
        remPt.setVisible(true);
    }//GEN-LAST:event_RemovePatientActionPerformed

    private void NewAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAppointmentActionPerformed
         NewAppointment2 appointmentFrame = new NewAppointment2();
        appointmentFrame.setVisible(true);
    }//GEN-LAST:event_NewAppointmentActionPerformed

    private void ListOfAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListOfAppointmentsActionPerformed
        ListOfAppointments appointmentFrame = new ListOfAppointments();
        appointmentFrame.setVisible(true);
    }//GEN-LAST:event_ListOfAppointmentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainClinicFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainClinicFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainClinicFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainClinicFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainClinicFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AppointmentMainMenu;
    private javax.swing.JMenu Billing;
    private javax.swing.JMenu DoctorMainMenu;
    private javax.swing.JMenuItem Insurance;
    private javax.swing.JMenuItem ListOfAppointments;
    private javax.swing.JMenuItem ListOfDoctors;
    private javax.swing.JMenuItem ListOfPatients;
    private javax.swing.JMenuItem NewAppointment;
    private javax.swing.JMenuItem NewDoctor;
    private javax.swing.JMenuItem NewPatient;
    private javax.swing.JMenu PatientMainMenu;
    private javax.swing.JMenuItem RemoveDoctor;
    private javax.swing.JMenuItem RemovePatient;
    private javax.swing.JMenuItem SearchDoctor;
    private javax.swing.JMenuItem SearchPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JPopupMenu jPopupMenu6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
